export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_PENDING = 'LOGIN_PENDING'

export const USERDATA_FAILED = 'USERDATA_FAILED'
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS'
export const USERDATA_PENDING = 'USERDATA_PENDING'

export const USERDATA_FILTER = 'USERDATA_FILTER'
